Bug #1852974 scripts: unisoc: rewrite the Sob check and add Author check
[root cause  ] add check whether the Sob contains Author
[changes     ] scripts
[side effects] no
[self test   ]: ikt
[download normally]: yes
[power on/off normally]: yes
[do common repository/branch inspection]: yes
[is there dependence]: no
[confirm dependent commit]: yes
[board]: sprd
[test case]: ikt
[reviewers   ] Orson.zhai
[change_type ] bringup --> sprd_chip_support
[tag_product ] common

Rewrite the Signature check
add check whether the Sob contains Author
Considering some patch from community or resigned staff.only
check oneof Sobs whether in the OSA, before is all Sob need
added into the OSA.

Test results for all situations:
No Sob:

ERROR: Signature(Signed-off-by) doesnot exist for commit message!!!
Please add the Singature by run command: git commit --amend -s

Author not on Sob:
ERROR: Signature not contain the Author!!!
Please add the Signature in commit message:Signed-off-by: Cixi Geng <cixi.geng1@unisoc.com>

None of the Sob in OSA:
ERROR: None of following signatures not in Documentation/unisoc/Open-Source-Agreement
['Xxxx Yy<xxxx.yy@unisoc.com>', 'Cixi Geng <cixi.geng1@unisoc.com>']

Change-Id: If68902fc07008263bf17c47d505c36b71f13ce50
Signed-off-by: Cixi Geng <cixi.geng1@unisoc.com>