Bug #1908558 pinctrl: sprd: add support buildin compile
[root cause  ] add buildin comdile
[changes     ] kernel
[side effects] no
[self test   ]: sprdebian
[download normally]: yes
[power on/off normally]: yes
[do common repository/branch inspection]: yes
[is there dependence]: yes
[confirm dependent commit]: yes
[board]: sprd
[test case]: ikt
[reviewers   ] cixi.geng
[change_type ] bringup --> sprd_chip_support
[tag_product ] common

if the sprd_soc builtin, the pinctrl-sprd also should built, or it
occur the built error as below:
aarch64-linux-gnu-ld: drivers/pinctrl/sprd/pinctrl-sprd-sharkl5Pro.o:
in function `sprd_pinctrl_probe':
drivers/pinctrl/sprd/pinctrl-sprd-sharkl5Pro.c:852:
undefined reference to `sprd_pinctrl_core_probe'

Change-Id: I792533f92893e8c9e585e7018e2cfffccf3304ed
Signed-off-by: Cixi Geng <cixi.geng1@unisoc.com>